const SITUACAO_SERVICO_KEYS = {
	TODAS: 'TODAS',
	ATIVO: 'ATIVO',
	INATIVO: 'INATIVO',
	EM_ANDAMENTO: 'EM_ANDAMENTO',
	CONCLUÍDO: 'CONCLUÍDO',
};

const SITUACAO_FUNCIONARIO_KEYS = {
	ATIVO: 'ATIVO',
	INATIVO: 'INATIVO',
	EM_LICENÇA: 'EM_LICENÇA',
};

const CATEGORIA_AVALIACAO_KEYS = {
	NENHUM: 'NENHUM',
	SUPERIOR: 'SUPERIOR',
	EXECUTOR: 'EXECUTOR',
};

const SITUACAO_FUNCIONARIO = {
	ATIVO: 'Ativa',
	INATIVO: 'Inativa',
	EM_LICENÇA: 'Em licença',
};

const SITUACAO_SERVICO = {
	TODAS: 'Todas',
	ATIVO: 'Ativa',
	INATIVO: 'Inativa',
	EM_ANDAMENTO: 'Em andamento',
	CONCLUÍDO: 'Concluída',
};

const SITUACAO_PARCIAL_SERVICO = {
	TODAS: 'Todas',
	INATIVO: 'Inativa',
	EM_ANDAMENTO: 'Em andamento',
	CONCLUÍDO: 'Concluída',
};

const CATEGORIA_AVALIACAO = {
	NENHUM: 'Nenhum',
	SUPERIOR: 'Superior',
	EXECUTOR: 'Executor',
};

export {
	SITUACAO_SERVICO_KEYS,
	SITUACAO_FUNCIONARIO_KEYS,
	CATEGORIA_AVALIACAO_KEYS,
	SITUACAO_SERVICO,
	SITUACAO_PARCIAL_SERVICO,
	SITUACAO_FUNCIONARIO,
	CATEGORIA_AVALIACAO,
};
